# Generated by Django 5.2 on 2025-05-25 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('room', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('caretakers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meal_distributions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.mealdistribution')),
            ],
        ),
    ]
