# Generated by Django 5.2 on 2025-05-25 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='meal_distributions',
        ),
    ]
