# Generated by Django 5.2 on 2025-05-25 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_mealdistribution_group'),
        ('group', '0002_remove_group_meal_distributions'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='meal_distributions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.mealdistribution'),
            preserve_default=False,
        ),
    ]
