# Generated by Django 5.2 on 2025-05-26 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_group_meal_distributions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='meal_distributions',
        ),
    ]
