# Generated by Django 5.2 on 2025-05-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='overall_kg',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
