# Generated by Django 5.2 on 2025-05-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventory_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='min_amount',
        ),
    ]
