# Generated by Django 5.2 on 2025-05-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=100)),
                ('district_name', models.CharField(default='local', max_length=100)),
                ('house_number', models.SmallIntegerField()),
            ],
        ),
    ]
