# Generated by Django 5.2 on 2025-05-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('caretaker', 'Caretaker'), ('chief', 'Chief')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
