# Generated by Django 5.2 on 2025-05-25 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        ('group', '0002_remove_group_meal_distributions'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealdistribution',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='group.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mealdistribution',
            name='served_day',
            field=models.DateTimeField(),
        ),
    ]
