# Generated by Django 5.2 on 2025-05-25 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_mealdistribution_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealdistribution',
            name='group',
        ),
    ]
