# Generated by Django 5.2 on 2025-05-26 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_mealdistribution_group'),
        ('group', '0004_remove_group_meal_distributions'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='group.group'),
            preserve_default=False,
        ),
    ]
