# Generated by Django 5.2 on 2025-05-26 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_meal_group'),
        ('group', '0004_remove_group_meal_distributions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='group',
        ),
        migrations.AddField(
            model_name='mealdistribution',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='group.group'),
            preserve_default=False,
        ),
    ]
